CODEOWNERS
Add Code Owners. PR reviews must need a mandatory PR approval from at-least 1 Code Owner.
=> Add Code Owners for the repo

README.md, canso-data-plane/canso-aws-eks-superchart/Chart.yaml
1. Adding a version bump for `can-aws-eks-superchart` for the changes merged in - https://github.com/Yugen-ai/canso-helm-charts/pull/15
2. Updating readme with a releases section.
=> [NOJIRA] Updating version for canso superchart

README.md, canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/templates/deployment.yaml, canso-data-plane/canso-agent/templates/required.yaml, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/README.md, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-airflow-jobs.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/ingress.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/jerry.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/karpenter.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/online-fs.yaml, canso-data-plane/canso-aws-eks-superchart/values.yaml
The `control_plane_role_arn` is used to access the sqs queqes on the Canso control plane. The policies for the same will be added during data-plane setup - see https://github.com/Yugen-ai/canso-data-plane-k8s-cluster-tf/blob/4d6fe24763201794f4b74b7bdd9209dbbe935c5d/canso-dataplane-configs/irsa-roles/canso-agent/auto.tfvars#L3
Note- Once the canso-agent is release, the updates will be made in the canso-superchart to install the agent with the latest chart
helm template for deployment-
```
helm template . &> template.txt
```
```
metadata:
name: canso-agent
labels:
helm.sh/chart: canso-agent-0.1.4
app.kubernetes.io/name: canso-agent
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: "0.0.1"
app.kubernetes.io/managed-by: Helm
spec: …
```
=> [NOJIRA] Adding control_plane_role_Arn to canso-agent config and required values

canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/jerry.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/karpenter.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/online-fs.yaml
Updating chart names in canso superchart -> from `canso-helm-charts/char-name` to `chart-name`
Testing in prod cluster with latest helm chart
=> [NOJIRA] Updating Chart names in canso superchart

canso-data-plane/canso-workflow-orchestrator/README.md, canso-data-plane/canso-workflow-orchestrator/values.yaml
Updated release version for the Canso Workflow Orchestrator.
=> Update Image tag for Workflow Orchestrator (Jerry)

canso-data-plane/canso-aws-eks-superchart/Chart.yaml
=> Canso Orchestrator Chart Release - `0.1.7`

canso-data-plane/canso-workflow-orchestrator/Chart.yaml
Fixes mistake in https://github.com/Yugen-ai/canso-helm-charts/pull/26
=> Canso Orchestrator Chart Update

canso-data-plane/canso-aws-eks-superchart/templates/aws/required.yaml
This PR updated the required values for the dataplane superchart. The values required for SQS are replaced with values required for RabbitMQ.
Merge the PR.
Run helm upgrade for data plane
Revert the PR
=> YP-838: Change superchart required values from sqs to rabbitmq

canso-data-plane/canso-aws-eks-superchart/Chart.yaml
This PR update the version for canso dplane superchart from 0.1.13 to 0.1.14
=> Bump Superchart Version

canso-data-plane/canso-task-server/Chart.yaml, canso-data-plane/canso-task-server/README.md, canso-data-plane/canso-task-server/values.yaml
This PR updates the image tag for canso-task-server to deploy changes done in https://github.com/Yugen-ai/canso-task-server/pull/6
=> Update image tag for canso-task-server

canso-data-plane/rule-evaluation-service/Chart.yaml, canso-data-plane/rule-evaluation-service/README.md, canso-data-plane/rule-evaluation-service/templates/redis.yaml, canso-data-plane/rule-evaluation-service/values.yaml
This PR implements the Redis deployment configuration in the Rule Evaluation Service Helm chart. Redis is needed to store and manage workflow rules and feature values used in transaction evaluation.
- Adds Redis deployment configuration using Bitnami Redis image
- Implements secure Redis access with password authentication
- Sets up Redis service for cluster communication
- Configures resource limits and requests for the Redis container
I have tested using helm template cmd.
<details><summary> Tested Result </summary>
<p>
```
---
apiVersion: v1
kind: Secret
metadata:
name: canso-rule-evaluation-service
labels:
type: Opaque
data:
redis-password: **********
---
apiVersion: v1
kind: Service
metadata:
name: canso-rule-evaluation-service
labels:
app: …
```
=> [NOJIRA]  Redis manifest for rule evaluations.

canso-data-plane/canso-rule-evaluation-service/Chart.yaml
Bump chart version from 0.0.9 to 0.0.10 with init job fixes
To be tested in the dataplane cluster
=> Bump chart version from 0.0.9 to 0.0.10 with init job fixes

canso-data-plane/canso-task-server/Chart.yaml, canso-data-plane/canso-task-server/README.md, canso-data-plane/canso-task-server/values.yaml
This PR updates the SHA tag for the canso task server docker image. 
This is being done to deploy the changes in https://github.com/Yugen-ai/canso-task-server/pull/7
=> Update the canso task server image SHA tag

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/README.md, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml, canso-data-plane/canso-task-server/Chart.yaml, canso-data-plane/canso-task-server/README.md, canso-data-plane/canso-task-server/values.yaml
This PR updates the image tags for canso agent and canso task server to deploy the changes in following PRs:
https://github.com/Yugen-ai/platform-dev-agent/pull/39
https://github.com/Yugen-ai/canso-task-server/pull/10
=> Update image tags for canso agent and canso task server

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/README.md, canso-data-plane/canso-agent/templates/redis.yaml, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml
Use image from shaktimaanbot account for redis
=> Use image from shaktimaanbot account for redis

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/templates/redis.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml
This PR adds image pull secret for redis deployment
=> Add image pull secret for redis deployment

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/README.md, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml
Switch back redis image that was being used previously - 7.2.5
=> Switch back redis image that was being used previously - 7.2.5

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/README.md, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml
- https://github.com/Yugen-ai/platform-dev-agent/pull/40
=> Update dev agent image to deploy utility apis

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/README.md, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml
This PR aims to deploy the following dev agent PR:
- https://github.com/Yugen-ai/platform-dev-agent/pull/41
=> Update dev agent image tag

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/README.md, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml
This PR updates the dev agent image tag to deploy the changes in following PR:
- https://github.com/Yugen-ai/platform-dev-agent/pull/46
=> Update dev agent image

canso-data-plane/canso-investigations-db/Chart.yaml, canso-data-plane/canso-investigations-db/templates/_helpers.tpl, canso-data-plane/canso-investigations-db/templates/job-db-migrations.yaml, canso-data-plane/canso-investigations-db/values.yaml
=> Canso Investigations DB - Flyway JDBC URL is now an Env variable

canso-data-plane/canso-fraud-analyst-service/Chart.yaml, canso-data-plane/canso-fraud-analyst-service/values.yaml
Fixed Correct Health Endpoints and service Port for fraud analyst service.
=> [NOJIRA] Fixed Correct Health Endpoints and service Port

canso-data-plane/canso-fraud-investigation-jobs/.helmignore, canso-data-plane/canso-fraud-investigation-jobs/Chart.yaml, canso-data-plane/canso-fraud-investigation-jobs/README.md, canso-data-plane/canso-fraud-investigation-jobs/templates/_helpers.tpl, canso-data-plane/canso-fraud-investigation-jobs/templates/deployment.yaml, canso-data-plane/canso-fraud-investigation-jobs/templates/image-pull-secret.yaml, canso-data-plane/canso-fraud-investigation-jobs/values.yaml
This PR adds a minimal helm chart for deploying canso-fraud-investigation-jobs.
<details>
<summary>Helm template Results:</summary>
```
---
metadata:
name: canso-fraud-inv-jobs
labels:
helm.sh/chart: canso-fraud-investigation-jobs-0.0.1
app.kubernetes.io/name: canso-fraud-investigation-jobs
app.kubernetes.io/instance: release-name
canso.ai/canso-fraud-inv-jobs-name: canso-fraud-inv-jobs
app.kubernetes.io/version: "v0.0.1"
app.kubernetes.io/managed-by: Helm
spec:
replicas: 1
selector:
matchLabels:
app.kubernetes.io/name: canso-fraud-investigation-jobs
app.kubernetes.io/instance: release-name
canso.ai/canso-fraud-inv-jobs-name: canso-fraud-inv-jobs
template:
metadata:
labels:
app.kubernetes.io/name: canso-fraud-investigation-jobs …
```
=> Add helm chart for Canso Fraud Investigation Jobs

canso-data-plane/canso-fraud-analyst-service/Chart.yaml, canso-data-plane/canso-fraud-analyst-service/templates/service.yaml, canso-data-plane/canso-fraud-analyst-service/values.yaml
Simplify fraud analyst service name
NA
=> Simplify fraud analyst service name
