canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/README.md, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-airflow-jobs/Chart.yaml, canso-data-plane/canso-airflow-jobs/README.md, canso-data-plane/canso-airflow-jobs/values.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-airflow-jobs.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/jerry.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/online-fs.yaml, canso-data-plane/canso-aws-eks-superchart/values.yaml, canso-data-plane/canso-online-feature-service/Chart.yaml, canso-data-plane/canso-online-feature-service/README.md, canso-data-plane/canso-online-feature-service/values.yaml, canso-data-plane/canso-workflow-orchestrator/Chart.yaml, canso-data-plane/canso-workflow-orchestrator/README.md, canso-data-plane/canso-workflow-orchestrator/values.yaml
Updates
- Updating secrets names from `stage/dockerhub` to `canso/dockerhub` in all charts
- Updating ingress service name for `online-fs` to `canso-online-feature`
Tested in canso-prod-dataplane-cluster
helm template output-
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: canso-online-feature-ing
namespace: online-fs
annotations:
helm.sh/hook: post-install
helm.sh/hook-weight: "10"
nginx.org/mergeable-ingress-type: "minion"
nginx.org/rewrites: serviceName=canso-online-feature rewrite=/    
spec:
ingressClassName: "nginx"  
rules:
- host: '*.com'
http:
paths:
- path: /online-fs/
pathType: Prefix
backend:
service:
name: canso-online-feature
port:
number: 80
```
external-secrets - 
```
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
name: …
```
=> [NOJIRA] Helm chart updates - secret manager - image updates - version bumps

canso-data-plane/canso-agent/templates/clusterrole.yaml
The Canso Agent should have the GET verb. Useful specially for debugging spark jobs.
=> Add GET verb to Canso Agent

canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/external-secrets-job.yaml
UPdating target type to `kubernetes.io/dockerconfigjson`. By default the secret created is of type `Opaque`
Manually updated on data-plane cluster and the image was successfully pulled. 
cc: @ashishYugen
=> [NOJIRA] Bugfix -Adding template type in External Secrets Job

canso-data-plane/canso-aws-eks-superchart/README.md, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/jerry.yaml, canso-data-plane/canso-aws-eks-superchart/values.yaml
- Bump the superchart version
- Superchart references latest Canso Agent release, for reference, see
- #22 
- https://github.com/Yugen-ai/canso-helm-charts/releases/tag/canso-agent-0.1.6
- https://github.com/Yugen-ai/canso-helm-charts/pull/25
- https://github.com/Yugen-ai/canso-helm-charts/pull/26
- https://github.com/Yugen-ai/canso-helm-charts/pull/27
- https://github.com/Yugen-ai/canso-helm-charts/releases/tag/canso-workflow-orchestrator-0.0.4
=> New Superchart Release to reference Canso Agent & Orchestrator releases

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/README.md, canso-data-plane/canso-agent/templates/_helpers.tpl, canso-data-plane/canso-agent/templates/celery-worker-deployment.yaml, canso-data-plane/canso-agent/templates/deployment.yaml, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-airflow-jobs/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/README.md, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-airflow-jobs.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/jerry.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/karpenter.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/online-fs.yaml, canso-data-plane/canso-aws-eks-superchart/values.yaml, canso-data-plane/canso-karpenter/Chart.yaml, canso-data-plane/canso-karpenter/README.md, canso-data-plane/canso-karpenter/values.yaml, canso-data-plane/canso-online-feature-service/Chart.yaml, canso-data-plane/canso-online-feature-service/README.md, canso-data-plane/canso-online-feature-service/templates/_helpers.tpl, canso-data-plane/canso-online-feature-service/templates/deployment.yaml, canso-data-plane/canso-online-feature-service/values.yaml, canso-data-plane/canso-workflow-orchestrator/Chart.yaml, canso-data-plane/canso-workflow-orchestrator/README.md, canso-data-plane/canso-workflow-orchestrator/templates/_helpers.tpl, canso-data-plane/canso-workflow-orchestrator/templates/deployment.yaml, canso-data-plane/canso-workflow-orchestrator/values.yaml
As we prep for release, we'll need to add SHA digests to image references in Helm charts/templates. We are going to use SHA digests instead of simple tags such as `latest` or `rc1` etc since they are floating in nature. This is [recommended by Helm as well](https://helm.sh/docs/chart_best_practices/pods/#images) & helps us to use our simpler Github trunk based workflows. Since SHA is immutable, we can merge PRs to main w/o impacting images running in Production unless we explicitly change the SHA in the tag.
Check how digests work on a simple nginx image by using SHA instead of tag.
```yaml
metadata:
name: nginx-deployment
labels:
app: nginx
spec:
replicas: 1
selector:
matchLabels:
app: nginx
template:
metadata:
labels:
app: nginx
spec:
containers:
- …
```
=> Use Image Digest to support Immutability + New Versions/Releases

canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/airflow.yaml
This PR adds a default AWS S3 connection named aws_default to our Airflow Helm chart configuration. 
This connection is set up with empty credentials, filled with actual credentials by the role_arn provided in the helm chart.
This solves the issue - https://github.com/Yugen-ai/canso-helm-charts/issues/30
airflow-webserver-pod
```
mishrasandeep@Sandeeps-MacBook-Pro ~ % kubectl exec -it airflow-web-6bd56bc9c6-2nhwr -n airflow -- env | grep AWS
Defaulted container "airflow-web" out of: airflow-web, check-db (init), wait-for-db-migrations (init)
AWS_STS_REGIONAL_ENDPOINTS=regional
AWS_REGION=***
AWS_DEFAULT_REGION=***
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_ROLE_ARN=arn:aws:iam::***:role/airflow-canso-dataplane-prod-irsa-role
```
Airlfow …
=> [Issue-30]Adding default s3 connection in airflow appset

canso-data-plane/canso-ai-agent/Chart.yaml, canso-data-plane/canso-ai-agent/README.md, canso-data-plane/canso-ai-agent/templates/NOTES.txt, canso-data-plane/canso-ai-agent/templates/_helpers.tpl, canso-data-plane/canso-ai-agent/templates/deployments.yaml, canso-data-plane/canso-ai-agent/templates/hpa.yaml, canso-data-plane/canso-ai-agent/templates/required.yaml, canso-data-plane/canso-ai-agent/templates/service.yaml, canso-data-plane/canso-ai-agent/values.yaml
This PR introduces a new Helm chart for deploying AI agent services to Kubernetes clusters. The chart is designed to be flexible, allowing users to easily configure and deploy AI agents with various settings
Features
- Configurable deployment with customizable number of replicas
- Horizontal Pod Autoscaler (HPA) for automatic scaling based on CPU or memory usage
- Customizable resource requests and limits
- Configurable liveness and readiness probes
Development indicators - 
- Chart version - 0.0.1-rc0
- NOTES.txt -  warning on installation
- README.md
tested on EKS cluster- 
**command** - 
```
helm install ai-agent-helm canso-data-plane/canso-ai-agent -n ai-agent-helm --create-namespace
```
**output** - 
```
NAME: ai-agent-helm
LAST DEPLOYED: Fri Aug  9 17:50:46 2024
NAMESPACE: …
```
=> [NOJIRA] Adding canso-ai-agent helm chart for deploying ai agents - RC1

canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/spark-operator.yaml
The SparkApplication currently created are facing issues due to an rc realease of the spark-operator helm chart - https://github.com/kubeflow/spark-operator/releases
The pod for the sparkApplication does not get created and the status for the Applications are not available.
This PR - 
1. Changes the Appset source to use the helm chart and version instead of github source and path
2. The helm chart source is updated to `https://kubeflow.github.io/spark-operator/` where the chart is now being served and the target revision is set to `1.4.6` which was the last stable version
**This change affects all the spark streaming Applications running in the dataplane.**
The Appset has been tested in the `data-plane` cluster
lastest sparkApplication run:
`kubectl get sparkapplications -n …
=> [NOJIRA] Updating spark operator AppSet to use chart keyword instead of path

canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/required.yaml, canso-data-plane/canso-aws-eks-superchart/values.yaml
The Superchart fails to install the canso agent helm chart if the secret name is changed on the dataplane. The changes fix this issue.
This PR-
1. Adds values from super chart values.yaml to override canso-agent default values.
2. Adds canso agent `cansoControlPlane` values to required.yaml
3. Update superchart version in Chart.yaml
command-
`helm template . &> template.txt`
output - 
```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
name: canso-agent
namespace: argocd
annotations:
argocd.argoproj.io/sync-wave: "5"
labels:
canso.ai/product-component: "canso-apps"
canso.ai/part-of: "superchart"
canso.ai/infra-component: "dataplane-agents"
canso.ai/infra-tag: "1002"
spec:
generators:
- list:
elements:
- cluster: 
url: https://kubernetes.default.svc
template:
metadata: …
```
=> [NOJIRA] Update ExternalSecret values for canso-agent in superchart

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/README.md, canso-data-plane/canso-agent/templates/_helpers.tpl, canso-data-plane/canso-agent/templates/celery-worker-deployment.yaml, canso-data-plane/canso-agent/templates/proxy-deployment.yaml, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/README.md, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml, canso-data-plane/canso-aws-eks-superchart/values.yaml
[YP-846](https://yugen-ai.atlassian.net/browse/YP-846)
This pull request introduces the Canso Agent Proxy Pod to enhance our architecture and improve the handling of requests. Additionally, the Helm chart version has been incremented to reflect these changes.
I generated the YAML for the proxy deployment pod using the Helm template command, and then I used the kubectl apply command to deploy the proxy pod for the staging development agent.
<details><summary> Generated Proxy Yaml </summary>
<p>
```yaml
metadata:
name: canso-agent-proxy
namespace: canso-agent-stage
labels:
helm.sh/chart: canso-agent-0.1.8
app.kubernetes.io/name: canso-agent
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: "v0.0.6-python-3.8-slim" …
```
=> [YP-846] Add Canso Agent Proxy Pod and Update Chart Version

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/README.md, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/README.md, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml, canso-data-plane/canso-aws-eks-superchart/values.yaml, canso-data-plane/canso-online-feature-service/Chart.yaml, canso-data-plane/canso-online-feature-service/README.md, canso-data-plane/canso-online-feature-service/values.yaml
Based on Synk recommendations, we're now using python 3.13 slim as the base image for all our services/applications. Pursuant to the image upgrade, we're making a new helm release as well.
- https://github.com/Yugen-ai/platform-services/pull/55
See https://github.com/Yugen-ai/platform-services/pull/55#issuecomment-2436285298
cc @Yugen-ai/platform-engineering
=> Online Feature Service, Agent & Superchart now reference app versions that point to python 3.13-slim base image for better security posture

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/README.md, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml
This PR updates the image version for dev agent deployments to the latest version. This is intended to deploy the issue fixed in https://github.com/Yugen-ai/platform-dev-agent/pull/33.
Follow instructions in [docs](https://docs.canso.ai/getting-started/canso-helm-charts#updating-the-chart)
Run `helm rollback`
=> Update dev agent image tag to latest

canso-data-plane/canso-ai-agent/Chart.yaml, canso-data-plane/canso-ai-agent/templates/deployments.yaml, canso-data-plane/canso-ai-agent/values.yaml
This PR adds single quotes to ai agent checkpoint db port number env variable. This is intended to avoid below error:
```
one or more objects failed to apply, reason: failed to create typed patch
object (ai-agents/agent1; apps/v1, Kind=Deployment):
.spec.template.spec.containers[name="agent1"].env[name="CHECKPOINT_DB_PORT"].value:
expected string, got &value.valueUnstructured{Value:5432}. Retrying
attempt #5 at 1:52PM
```
Will be tested in staging env.
=> Add single quotes to ai agent checkpoint db port number env variable

canso-data-plane/rule-evaluation-service/Chart.yaml, canso-data-plane/rule-evaluation-service/README.md, canso-data-plane/rule-evaluation-service/templates/redis.yaml, canso-data-plane/rule-evaluation-service/values.yaml
This PR
1. Adds a suffix `-redis` to the redis deployment and service in the rule evaluation service helm chart
2. Disable the auth by default
3. Updates a few values.yaml that needed to be updated in the management service
4. Bumps the chart version
<details><summary>helm template . </summary>
<p>
```
---
---
apiVersion: v1
kind: Service
metadata:
name: canso-rule-evaluation-service-redis
labels:
spec:
type: NodePort
ports:
- port: 6379
targetPort: redis
protocol: TCP
name: redis
selector:
---
apiVersion: v1
kind: Service
metadata:
name: canso-rule-evaluation-service
spec:
type: NodePort
selector:
app: canso-rule-evaluation-service
ports:
- name: http
port: 80
protocol: TCP …
```
=> [NOJIRA] Updating values.yaml and redis service

canso-data-plane/rule-evaluation-service/Chart.yaml, canso-data-plane/rule-evaluation-service/README.md, canso-data-plane/rule-evaluation-service/values.yaml
1. We are removing the auth here due to secret issues in the dev agent.
2. The bitnami/redis image requires the auth for deployment. So we are now using the official redis image instead
Applied the deployment template in the dataplane cluster
```
metadata:
name: canso-rule-evaluation-service-redis
namespace: default
labels:
spec:
replicas: 1
selector:
matchLabels:
template:
metadata:
labels:
spec:
containers:
- name: redis
image: "redis:7.4.2"
imagePullPolicy: IfNotPresent
ports:
- name: redis
containerPort: 6379
protocol: TCP
env:
resources:
limits:
cpu: 200m
memory: 256Mi
requests:
cpu: 100m
memory: 128Mi
```
=> [NOJIRA] Remove auth and change redis image

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/README.md, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml
- Update image tags in values.yaml for canso-agent
- Bump canso-agent chart version from 0.1.13 to 0.1.14
- Bump canso-aws-eks-superchart chart version from 0.1.18 to 0.1.19
- Update targetRevision for canso-agent in canso-aws-eks-superchart
Tested in the daplane cluster - staging dev agent
1. Merge the PR
2. Check the gh-pages for new releses
3. Update the suprechart in the dataplane for prod dev agent
1. Revert the PR
2. Delete the relases for the cano-agent and superchart charts
=> Update image tags for canso-agent and  helm chart versions for canso-aws-eks-superchart

canso-data-plane/canso-rule-evaluation-service/Chart.yaml, canso-data-plane/canso-rule-evaluation-service/README.md, canso-data-plane/canso-rule-evaluation-service/templates/config-map-init.yaml, canso-data-plane/canso-rule-evaluation-service/templates/ingress.yaml, canso-data-plane/canso-rule-evaluation-service/values.yaml
This PR fixes the ingress path conflict issues. Since multiple paths were deployed at  `v1/risk` the endpoint was thwoing an error.
Now the endpoint has the nameOverride added in the path `{{ include "canso-rule-evaluation-service.name" . }}{{ .Values.ingress.path }}`
Changes
- Modified ingress.yaml to adjust the path for the service name.
- Incremented the chart version in Chart.yaml to 0.0.8.
- Disabled the Redis initialization job and persistence in values.yaml.
- Updated config-map-init.yaml to conditionally include initialization logic based on the new Redis settings.
Tested in the dataplane cluster
```
helm install risk-test-ing /Users/mishrasandeep/Documents/canso-helm-charts/canso-helm-charts/canso-data-plane/canso-rule-evaluation-service --set namespaceOverride=risk-test-ing -n …
```
=> [NOJIRA]Bump chart version to 0.0.8 and update RIsk ingress

canso-data-plane/canso-rule-evaluation-service/Chart.yaml, canso-data-plane/canso-rule-evaluation-service/templates/service.yaml
Added Prometheus discovery annotations in a serverYAML file and bumped chart version.
Tested using helm template cmd.
<details><summary> Template Response </summary>
<p>
```
---
---
apiVersion: v1
kind: Service
metadata:
name: canso-rule-evaluation-service-redis
labels:
spec:
type: NodePort
ports:
- port: 6379
targetPort: redis
protocol: TCP
name: redis
selector:
---
apiVersion: v1
kind: Service
metadata:
name: canso-rule-evaluation-service
annotations:
prometheus.io/scrape: "true"
prometheus.io/port: "8000"
prometheus.io/path: "/metrics"
prometheus.io/scheme: "http"
spec:
type: NodePort
selector:
app: canso-rule-evaluation-service
ports:
- name: http …
```
=> [NOJIRA] Update Chart version and add annotations

canso-data-plane/canso-rule-evaluation-service/README.md, canso-data-plane/canso-rule-evaluation-service/templates/redis-init-job.yaml, canso-data-plane/canso-rule-evaluation-service/values.yaml
Adding argocd hooks to the redis-init-job
helm template
```
apiVersion: batch/v1
kind: Job
metadata:
name: canso-rule-evaluation-service-redis-init
annotations:
"helm.sh/hook": post-install,post-upgrade
"helm.sh/hook-delete-policy": before-hook-creation
"argocd.argoproj.io/hook": Sync
"argocd.argoproj.io/hook-delete-policy": BeforeHookCreation, HookSucceeded
"argocd.argoproj.io/sync-wave": "1"
spec:
template:
spec:
restartPolicy: Never
containers:
- name: redis-init
image: python:3.12-slim
command: ["sh", "-c"]
args:
- |
pip install redis &&
python /scripts/redis-init.py
volumeMounts:
- name: redis-init-script
mountPath: /scripts
volumes:
- name: redis-init-script
configMap:
name: canso-rule-evaluation-service-redis-init-script
env:
```
=> [NOJIRA] Add Argocd hooks for risk init job

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/README.md, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml
This PR updates the docker image tag of the canso dev agent application.
This is intended to deploy the changes in https://github.com/Yugen-ai/platform-dev-agent/pull/38
=> Update the canso dev agent image tag

canso-data-plane/canso-rule-evaluation-service/Chart.yaml, canso-data-plane/canso-rule-evaluation-service/README.md, canso-data-plane/canso-rule-evaluation-service/templates/deployment.yaml, canso-data-plane/canso-rule-evaluation-service/templates/hpa.yaml, canso-data-plane/canso-rule-evaluation-service/values.yaml
This PR adds HPA to the Rule Evaluation Service, allowing it to automatically adjust the number of pods based on CPU and memory usage. This improvement boosts resource efficiency and enhances service reliability during fluctuating workloads.
I have tested using helm template cmd.
<details><summary> Helm Template Result </summary>
<p>
```
---
apiVersion: v1
kind: ConfigMap
metadata:
name: canso-rule-evaluation-service-redis-init-script
data:
redis-init.py: |
import redis
import json
import time
def connect_to_redis_with_retries(host, port, retries=6, delay=10):
for attempt in range(1, retries + 1):
try:
client = redis.Redis(host=host, port=port, socket_connect_timeout=5)
client.ping()  
return client
except redis.ConnectionError as e:
if attempt < retries: …
```
=> [NOJIRA] Add Horizontal Pod Autoscaling (HPA) to Rule Evaluation Service

canso-data-plane/canso-ai-agent/Chart.yaml, canso-data-plane/canso-ai-agent/README.md, canso-data-plane/canso-ai-agent/templates/deployments.yaml, canso-data-plane/canso-ai-agent/templates/serviceaccount.yaml, canso-data-plane/canso-ai-agent/values.yaml
This Pr-
1. Adds a service account to the canso-ai-agent helm chart
2. Adds optional role Arn in the service account from values.yaml
3. Bumps the chart version from 0.1.2 to 0.1.3
Tested on data plane
```
helm install /Users/mishrasandeep/Documents/canso-helm-charts/canso-helm-charts/canso-data-plane/canso-ai-agent -f agent-values.yaml --generate-name
```
**ServiceAccount** 
**Deployment**
1. Merge the PR
2. Verify github action new release
3. Veify installation with the new release
1. Revert the PR
2. Delete the released version from the index.yaml and the releases artifact
=> Add service account and optional aws roleArn

canso-data-plane/canso-rule-evaluation-service/Chart.yaml, canso-data-plane/canso-rule-evaluation-service/README.md, canso-data-plane/canso-rule-evaluation-service/values.yaml
Set False Redis init jobs for Rule evaluation service.
I have tested using helm template cmd
<details><summary> Helm Template Result </summary>
<p>
```
---
---
apiVersion: v1
kind: Service
metadata:
name: canso-rule-evaluation-service-redis
labels:
spec:
type: NodePort
ports:
- port: 6379
targetPort: redis
protocol: TCP
name: redis
selector:
---
apiVersion: v1
kind: Service
metadata:
name: canso-rule-evaluation-service
annotations:
prometheus.io/scrape: "true"
prometheus.io/port: "8000"
prometheus.io/path: "/metrics"
prometheus.io/scheme: "http"
spec:
type: NodePort
selector:
app: canso-rule-evaluation-service
ports:
- name: http
port: 80
protocol: TCP …
```
=> [NOJIRA] Set False init Jobs for rule evaluation

canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/README.md, canso-data-plane/canso-aws-eks-superchart/templates/aws/metrics-server.yaml, canso-data-plane/canso-aws-eks-superchart/values.yaml
I’ve added the metrics server to the ArgoApplication set and updated the values.yaml file with the appropriate configurations.
Have tested using Helm cmd
<details><summary> Result </summary>
<p>
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
name: metrics-server
namespace: argocd
annotations:
helm.sh/hook: pre-install
helm.sh/hook-weight: "-19"
argocd.argoproj.io/sync-wave: "-5"
labels:
canso.ai/product-component: "infra-dependencies"
canso.ai/part-of: "superchart"
canso.ai/infra-component: "metrics-server"
canso.ai/infra-tag: "1000"
spec:
generators:
- list:
elements:
- cluster: canso-dplane-v1
url: https://kubernetes.default.svc
template:
metadata:
name: metrics-server
spec:
project: canso-appsets
destination:
namespace: kube-system
server: …
```
=> [NOJIRA] Add metrics server for HPA

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/templates/clusterrole.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml
In line with 
- https://github.com/Yugen-ai/platform-dev-agent/pull/40 and 
- https://github.com/Yugen-ai/canso-cplane-agents-service/pull/13, 
the Canso dev agent needs to be able to update and delete argocd applications. This PR updates the dev agent cluster role to be able to do that.
=> Update dev agent cluster role to update and delete applications

canso-data-plane/canso-ai-agent/Chart.yaml, canso-data-plane/canso-ai-agent/templates/deployments.yaml, canso-data-plane/canso-ai-agent/values.yaml
This PR changes the way env variables are supplied to the AI Agent. 
Instead of supplying individual values, env variables are supplied as a map.
This prevents us needing to update the helm chart everytime we want to add a new env variable to the the AI agent.
Merge the PR
Revert the PR
=> AI Agent: Supply env variables as map instead of individual values

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/README.md, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml
- This will release the latest code for Dev Agent with Memory Operation Strategy in PROD
- https://github.com/Yugen-ai/canso-cplane-agents-service/pull/17
- All the test results are attached here
- https://github.com/Yugen-ai/platform-k8s-gitops-apps/pull/398
Standard PR merge.
Standard PR revert.
=> Upgraded Dev Agent version to support Latest Memory APIs

canso-data-plane/canso-ai-agent/Chart.yaml, canso-data-plane/canso-ai-agent/README.md, canso-data-plane/canso-ai-agent/templates/deployments.yaml, canso-data-plane/canso-ai-agent/templates/hpa.yaml, canso-data-plane/canso-ai-agent/values.yaml
This PR adds HPA to the AI Agent, allowing it to automatically adjust the number of pods based on CPU and memory usage. This improvement boosts resource efficiency and enhances service reliability during fluctuating workloads.
I have tested using helm template cmd.
<details><summary> Helm Template Result </summary>
<p>
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: -sa
labels:
helm.sh/chart: canso-ai-agent-0.1.5
app.kubernetes.io/name: canso-ai-agent
app.kubernetes.io/instance: release-name
canso.ai/agent-name : 
app.kubernetes.io/version: "0.0.1"
app.kubernetes.io/managed-by: Helm
annotations:
---
apiVersion: v1
kind: Service
metadata:
name: 
labels:
helm.sh/chart: canso-ai-agent-0.1.5
app.kubernetes.io/name: canso-ai-agent
app.kubernetes.io/instance: release-name …
```
=> [NOJIRA] Add HPA for canso ai agent

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/README.md, canso-data-plane/canso-agent/templates/celery-worker-deployment.yaml, canso-data-plane/canso-agent/templates/deployment.yaml, canso-data-plane/canso-agent/templates/redis.yaml, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml
See 
- https://github.com/Yugen-ai/platform-dev-agent/issues/44
- https://github.com/Yugen-ai/platform-dev-agent/pull/45
TBU
TODOs
A longstanding issue we have had in the Canso Dev Agent is that Celery broker and backend URLs have been hardcoded in the application. Since we run 2 Dev agents in the data plane (one for staging & prod each), the hardcoded Broker & Backend URLs cause the staging Dev Agent to interact with the Prod celery & redis.
This caused issues when the Dev Agent refactor was being tested. We had to hardcode the URLs to the staging values to then see the logs in the Dev Agent and Celery PODs.
This PR makes a longer term fix so that we can manage both deployments of Dev Agents in the Data Plane independently. In both the Celery Worker & Dev Agent Deployment, we're adding …
=> New Canso Dev Agent Helm Release (Alpha version)

.github/workflows/docs.yaml, canso-data-plane/canso-fraud-analyst-service/.helmignore, canso-data-plane/canso-fraud-analyst-service/Chart.yaml, canso-data-plane/canso-fraud-analyst-service/templates/NOTES.txt, canso-data-plane/canso-fraud-analyst-service/templates/_helpers.tpl, canso-data-plane/canso-fraud-analyst-service/templates/configmap.yaml, canso-data-plane/canso-fraud-analyst-service/templates/deployment.yaml, canso-data-plane/canso-fraud-analyst-service/templates/hpa.yaml, canso-data-plane/canso-fraud-analyst-service/templates/ingress.yaml, canso-data-plane/canso-fraud-analyst-service/templates/service.yaml, canso-data-plane/canso-fraud-analyst-service/templates/serviceaccount.yaml, canso-data-plane/canso-fraud-analyst-service/templates/tests/test-connection.yaml, canso-data-plane/canso-fraud-analyst-service/values.yaml
- Helm create for scaffolding
- Documentation for readme generator CI
- Deployment YAML & Values updated to support expected env variables
- Configmaps added & corresponding volume & volume mount in deployment updated. Values YAML don't have default values.
```console
(base) ➜  canso-fraud-analyst-service git:(canso-fraud-analyst-svc-helm) ✗ helm lint
==> Linting .
[INFO] Chart.yaml: icon is recommended
1 chart(s) linted, 0 chart(s) failed
```
=> First Helm release of the Canso Fraud Analyst Service (AI Agent based Investigations)

canso-data-plane/canso-investigations-db/Chart.lock
Remove chart lock. This is not needed and was the root cause behind the failed github action run [here](https://github.com/Yugen-ai/canso-helm-charts/actions/runs/14733554742)
=> BugFix - Canso DB Migrations - Delete older Chart Lock

canso-data-plane/canso-fraud-analyst-service/Chart.yaml, canso-data-plane/canso-fraud-analyst-service/values.yaml
Fixes the following error. Requests & Limits values were interchanged.
```sh
one or more objects failed to apply, reason: Deployment.apps
"fraud-analyst-service-canso-fraud-analyst-service" is invalid:
[spec.template.spec.containers[0].resources.requests: Invalid value:
"750m": must be less than or equal to cpu limit of 400m,
spec.template.spec.containers[0].resources.requests: Invalid value:
"768Mi": must be less than or equal to memory limit of 384Mi].
```
cc @Yugen-ai/platform-engineering
=> Canso Fraud Analyst Service - Fix Requests<=Limits

canso-data-plane/canso-fraud-analyst-service/Chart.yaml, canso-data-plane/canso-fraud-analyst-service/templates/deployment.yaml, canso-data-plane/canso-fraud-analyst-service/values.yaml
Addresses feedback & TODO discussed [here](https://github.com/Yugen-ai/canso-helm-charts/pull/89#discussion_r2065791530).
Additionally, this will help address the issue where the expected env variable is incorrectly set to `CANSO_INVESTIGATIONS_DATABASE`, but should be `CANSO_INVESTIGATIONS_DB`
cc @Yugen-ai/platform-engineering
=> Flexible env variables for the Canso Fraud Analyst

canso-data-plane/canso-investigations-db/Chart.yaml, canso-data-plane/canso-investigations-db/templates/_helpers.tpl, canso-data-plane/canso-investigations-db/templates/job-db-migrations.yaml, canso-data-plane/canso-investigations-db/values.yaml
- Finalise Environment variables (Init container + Flyway)
- Init Container now references postgres via env variables (this is a prior component deploy step in our system)
- Flyway configs moved to env variables as well
- Update `postgresql.jdbcUrl` to use env variables
- Appropriate Requests & Limits for the Flyway POD (Warning on JVM added)
- Tests done on a local minkube cluster
```sh
(base) ➜  canso-investigations-db git:(flyway-migration-fixes) ✗ helm install db-migration . \
--set dbSchemaSetup.image.repository="shaktimaanbot/canso-fraud-analyst-service" \
--set dbSchemaSetup.image.tag="db-v0.1.0-flyway-11.8-alpine" \
--set dbSchemaSetup.enabled=true \
--set env.postgresInit.PG_HOST="canso-db-postgresql-primary" \
--set env.postgresInit.PG_USER="postgres" \
--set …
```
=> Improved version of the Canso Investigations DB Helm chart

canso-data-plane/canso-investigations-db/Chart.yaml, canso-data-plane/canso-investigations-db/templates/job-db-migrations.yaml
We noticed that the ArgoCD application gets created in the data plane and is synced + healthy, but the DB migration job isn't created. This PR will likely solve this issue.
cc @ashishYugen
=> Canso Investigations DB - Remove Hooks to make DB Migrations Job run independently

canso-data-plane/canso-investigations-db/Chart.yaml, canso-data-plane/canso-investigations-db/templates/job-db-migrations.yaml
While running the DB migrations job in the data plane, we came across the following error -
```sh
.spec.template.spec.containers[name="flyway-migrate"].env[name="FLYWAY_P │
│ ASSWORD"].valueFrom.secretKeyRef.namespace: field not declared in schema (retried 5 times).
```
`namespace` is not a valid input inside `secretKeyRef`. This PR fixes that.
=> Canso Investigations DB - `secretKeyRef` doesn't support cross-namespace references

canso-data-plane/canso-investigations-db/Chart.yaml, canso-data-plane/canso-investigations-db/templates/_helpers.tpl, canso-data-plane/canso-investigations-db/templates/job-db-migrations.yaml
Had created the helm chart using the `helm create` template and had forgotten to add the helper that supports image tags/SHAs in deployment - this is something we have followed in most of our charts.
cc @Yugen-ai/platform-engineering
=> Support both image tags & SHAs in Canso Investigations DB

canso-data-plane/canso-agent/Chart.yaml, canso-data-plane/canso-agent/README.md, canso-data-plane/canso-agent/values.yaml, canso-data-plane/canso-aws-eks-superchart/Chart.yaml, canso-data-plane/canso-aws-eks-superchart/templates/aws/canso-agent.yaml
- As part of the fraud analyst service deployments we have observed that we need the functionality to send list of strings as parameters in GET requests. To enable this in the HTTPExecutor we have made the corresponding changes  ([See this](https://github.com/Yugen-ai/platform-dev-agent/pull/60)) 
- In this PR we have made the changes to the chart versions so that the latest dev agent version with the relevant changes are picked up
<details>
<summary> Output of helm dry run and local commands</summary>
- Current list and revisions output
- Dry run output
- Updated tags in the dry run output
</details>
- Directly Merge to master
=> New Canso Dev Agent Helm Release (v0.1.2)

canso-data-plane/canso-fraud-analyst-service/Chart.yaml, canso-data-plane/canso-fraud-analyst-service/values.yaml
Update the correct AWS secret name for Docker Hub credentials.
<details><summary> helm template . -f values.yaml > template.txt </summary>
<p>
```yaml
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
name: canso-dockerhub-credentials-es
namespace: default
spec:
refreshInterval: 1m
secretStoreRef:
name: secretstore-by-role
kind: ClusterSecretStore
target:
name: canso-dockerhub-credentials
creationPolicy: Owner
template:
type: kubernetes.io/dockerconfigjson
data:
- secretKey: .dockerconfigjson
remoteRef:
key: canso-dockerhub-credentials
property: dockerhub
---
```
</p>
</details>
1. Standard PR merge and automatically release the new version of the helm chart
2. Deploy fraud analyst services with the new chart version.
1. Standard PR revert.
2. Delete the new …
=> [NOJIRA] Fix Correct aws secret name for Dockerhub cred
